### PR TITLE
Remove redundant Quat and SPQuat types

### PR DESCRIPTION
**Pull request by bjack205**
This deprecates `Quat` and `SPQuat` in favor of `UnitQuaterion` and `MRP`, per #112. 

These newer types were introduced in #113 and add more functionality and performance to the original types (see https://github.com/JuliaGeometry/Rotations.jl/pull/113#issue-392750215).

### CODE REVIEW

**Comment by c42f** [comment]
Looks good to me. One thought: it would be nice if we had some better naming consistency between `MRP` and `RodriguesParam`. `ModifiedRodriguesParam` is the obvious more-explicit alternative but it's kind of annoying to type. Are there other alternatives?

**Comment by bjack205** [comment]
`MRP` is pretty standard in the literature, and I agree that writing out `ModifiedRodriguesParam` is annoying to type. I see your point that more naming consistency would be nice, but in fact the literature typically follows the convention I used (abbreviated MRP and written-out Rodrigues parameter). Rodrigues parameters are also commonly called Gibbs vectors so we could use `GibbsVector` instead to avoid the apparent inconsistency.

**Comment by zygmuntszpak** [comment]
Thanks for all the great work. Perhaps its worth tagging a new release? I just came upon this library and was confused why the MRP examples in the documentation didn't work.

**Comment by c42f** [comment]
@bjack205 deserves all the credit for the recent work!

Regarding release, agreed - see #112

**Pull request merged**
